In [1]:
import os

import numpy as np
import pandas as pd
import pymongo

In [2]:
year = 2019
short_year = year - 2000
summary = os.path.join('data', 'SeasonSummary', f'summary{short_year}.csv')

In [5]:
summary_df = pd.read_csv(summary)
summary_df.head()

,Season,TeamName,Tempo,RankTempo,AdjTempo,RankAdjTempo,OE,RankOE,AdjOE,RankAdjOE,DE,RankDE,AdjDE,RankAdjDE,AdjEM,RankAdjEM
0,2019,Abilene Christian,66.4788,295,66.0678,257,105.8270,111,103.3550,195,97.6435,48,102.1230,126,1.23262,152
1,2019,Air Force,67.2794,267,66.4915,235,98.7687,275,100.6130,252,105.6820,242,107.6620,241,-7.04918,243
2,2019,Akron,68.4518,205,66.1133,254,99.4248,264,99.9275,261,94.0099,11,94.1434,22,5.78410,108
3,2019,Alabama,69.8011,128,68.6281,118,102.5150,185,108.0880,106,102.3050,154,97.5645,61,10.52320,65
4,2019,Alabama A&M,67.5600,251,65.5769,283,88.7657,347,86.7728,350,104.8620,215,109.3620,265,-22.58890,344

In [ ]:
ff_offense = os.path.join('data', 'FourFactors', 'Offense', '')