# Scraping KenPom HCA page

In [13]:
import pandas as pd
from splinter import Browser
from bs4 import BeautifulSoup
import os
import glob
from config import user, pwd
import numpy as np

In [2]:
def init_browser():
    # Mac-specific browser init
    executable_path = {'executable_path': '/usr/local/bin/chromedriver'}
    browser = Browser('chrome', **executable_path, headless=False)
    return browser

In [3]:
url = 'https://kenpom.com'
password = pwd
email = user
browser = init_browser()
browser.visit(url)

In [4]:
browser.find_by_name('email').fill(email)
browser.find_by_name('password').fill(password)
browser.find_by_name('submit').first.click()

In [5]:
url2 = 'https://kenpom.com/hca.php'
browser.visit(url2)

In [6]:
# Scrape the page
soup = BeautifulSoup(browser.html, 'lxml')
browser.quit()
headline_list = [] # Store the headlines

# Find the table
table = soup.find_all('table')[0]

In [7]:
df = pd.read_html(str(table))

In [8]:
df[0].head()

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
                Team               Conf                HCA                HCA
                Team               Conf                HCA                HCA
                Team               Conf                HCA                HCA
                Team               Conf                HCA                HCA
                Team               Conf                HCA                HCA
                Team               Conf                HCA                HCA
                Team               Conf                HCA                HCA
                Team               Conf                HCA                HCA
                Team               Conf                HCA                HCA
0     Louisiana Tech               CUSA                4.5                  1
1           Colorado                P12                4.5                  2
2      West Virginia                B12                4.3                  3
3       Illinois St.                MVC                4.2                  4
4           Kentucky                SEC                4.2                  5

  Model inputs(based on last 60 home and road conf. games)Values are per game differencesbetween home and road margin  \
                                                                                                                   PF
                                                                                                                   PF
                                                                                                                   PF
                                                                                                                   PF
                                                                                                                   PF
                                                                                                                   PF
                                                                                                                   PF
                                                                                                                   PF
                                                                                                                   PF
0                                               -4.2
1                                               -4.0
2                                               -4.7
3                                               -5.3
4                                               -4.3


         Pts        NST        Blk        Elev
         Pts        NST        Blk        Elev
         Pts        NST        Blk        Elev
         Pts        NST        Blk        Elev
         Pts        NST        Blk        Elev
         Pts        NST        Blk        Elev
         Pts        NST        Blk        Elev
         Pts        NST        Blk        Elev
  PF.1   Pts Pts.1  NST NST.1  Blk Blk.1  Elev Elev.1
0   41  13.1     2 -2.2    11  2.9     1   300    210
1   51  12.7     3 -1.1   128  2.2    22  5400      5
2   15  10.7    13 -2.4     7  2.0    30  1000     58
3    2  11.1     8 -2.0    17  0.9   259   800     91
4   33  11.8     5 -0.9   152  2.4    13  1000     58

# Getting team names from Sportsref

In [9]:
from sportsreference.ncaab.teams import Teams

teams = Teams()
for team in teams:
#     print(team.abbreviation.lower())

abilene-christian
air-force
akron
alabama-am
alabama-birmingham
alabama-state
alabama
albany-ny
alcorn-state
american
appalachian-state
arizona-state
arizona
arkansas-little-rock
arkansas-pine-bluff
arkansas-state
arkansas
army
auburn
austin-peay
ball-state
baylor
belmont
bethune-cookman
binghamton
boise-state
boston-college
boston-university
bowling-green-state
bradley
brigham-young
brown
bryant
bucknell
buffalo
butler
cal-poly
cal-state-bakersfield
cal-state-fullerton
cal-state-northridge
california-baptist
california-davis
california-irvine
california-riverside
california-santa-barbara
california
campbell
canisius
central-arkansas
central-connecticut-state
central-florida
central-michigan
charleston-southern
charlotte
chattanooga
chicago-state
cincinnati
citadel
clemson
cleveland-state
coastal-carolina
colgate
college-of-charleston
colorado-state
colorado
columbia
connecticut
coppin-state
cornell
creighton
dartmouth
davidson
dayton
delaware-state
delaware
denver
depaul
detroit-mercy
drake
drexel
duke
duquesne
east-carolina
east-tennessee-state
eastern-illinois
eastern-kentucky
eastern-michigan
eastern-washington
elon
evansville
fairfield
fairleigh-dickinson
florida-am
florida-atlantic
florida-gulf-coast
florida-international
florida-state
florida
fordham
fresno-state
furman
gardner-webb
george-mason
george-washington
georgetown
georgia-southern
georgia-state
georgia-tech
georgia
gonzaga
grambling
grand-canyon
green-bay
hampton
hartford
harvard
hawaii
high-point
hofstra
holy-cross
houston-baptist
houston
howard
idaho-state
idaho
illinois-chicago
illinois-state
illinois
incarnate-word
indiana-state
indiana
iona
iowa-state
iowa
ipfw
iupui
jackson-state
jacksonville-state
jacksonville
james-madison
kansas-state
kansas
kennesaw-state
kent-state
kentucky
la-salle
lafayette
lamar
lehigh
liberty
lipscomb
long-beach-state
long-island-university
longwood
louisiana-lafayette
louisiana-monroe
louisiana-state
louisiana-tech
louisville
loyola-il
loyola-marymount
loyola-md
maine
manhattan
marist
marquette
marshall
maryland-baltimore-county
maryland-eastern-shore
maryland
massachusetts-lowell
massachusetts
mcneese-state
memphis
mercer
miami-fl
miami-oh
michigan-state
michigan
middle-tennessee
milwaukee
minnesota
mississippi-state
mississippi-valley-state
mississippi
missouri-kansas-city
missouri-state
missouri
monmouth
montana-state
montana
morehead-state
morgan-state
mount-st-marys
murray-state
navy
nebraska-omaha
nebraska
nevada-las-vegas
nevada
new-hampshire
new-mexico-state
new-mexico
new-orleans
niagara
nicholls-state
njit
norfolk-state
north-alabama
north-carolina-asheville
north-carolina-at
north-carolina-central
north-carolina-greensboro
north-carolina-state
north-carolina-wilmington
north-carolina
north-dakota-state
north-dakota
north-florida
north-texas
northeastern
northern-arizona
northern-colorado
northern-illinois
northern-iowa
northern-kentucky
northwestern-state
northwestern
notre-dame
oakland
ohio-state
ohio
oklahoma-state
oklahoma
old-dominion
oral-roberts
oregon-state
oregon
pacific
penn-state
pennsylvania
pepperdine
pittsburgh
portland-state
portland
prairie-view
presbyterian
princeton
providence
purdue
quinnipiac
radford
rhode-island
rice
richmond
rider
robert-morris
rutgers
sacramento-state
sacred-heart
saint-francis-pa
saint-josephs
saint-louis
saint-marys-ca
saint-peters
sam-houston-state
samford
san-diego-state
san-diego
san-francisco
san-jose-state
santa-clara
savannah-state
seattle
seton-hall
siena
south-alabama
south-carolina-state
south-carolina-upstate
south-carolina
south-dakota-state
south-dakota
south-florida
southeast-missouri-state
southeastern-louisiana
southern-california
southern-illinois-edwardsville
southern-illinois
southern-methodist
southern-mississippi
southern-utah
southern
st-bonaventure
st-francis-ny
st-johns-ny
stanford
stephen-f-austin
stetson
stony-brook
syracuse
temple
tennessee-martin
tennessee-state
tennessee-tech
tennessee
texas-am-corpus-christi
texas-am
texas-arlington
texas-christian
texas-el-paso
texas-pan-american
texas-san-antonio
texas-southern
texas-state
texas-tech
texas
toledo
towson
troy
tulane
tulsa
ucla
utah-state
utah-valley
utah
valparaiso
vanderbilt
vermont
villanova
virginia-commonwealth
virginia-military-institute
virginia-tech
virginia
wagner
wake-forest
washington-state
washington
weber-state
west-virginia
western-carolina
western-illinois
western-kentucky
western-michigan
wichita-state
william-mary
winthrop
wisconsin
wofford
wright-state
wyoming
xavier
yale
youngstown-state

# Getting unique team names from all the Kenpom data

In [10]:
df1 = pd.DataFrame()
# Change directory
data_loc = "./data/cleaned"#input("Enter the path for your download directory: ")
try:
    os.chdir(data_loc)
except FileNotFoundError:
    print("Please change the directory to the location of your results files")

# List all files and directories in current directory
files = glob.glob((data_loc + "/*.csv").split("/")[-1])
print(files)

['master_2011.csv', 'master_2010.csv', 'master_2012.csv', 'master_2013.csv', 'master_2017.csv', 'master_2016.csv', 'master_2014.csv', 'master_2015.csv', 'master_2018.csv', 'master_2019.csv']

In [11]:
file_count = 0
for item in files:

    xl = pd.read_csv(item)
    df1 = df1.append(xl, ignore_index=True, sort=False)
    # Get the portion of the filename
    file_count += 1
    # Load a sheet into a DataFrame by name: df1

In [12]:
file_count

10

In [13]:
df1.head()

,TeamName,Season,Tempo,RankTempo,AdjTempo,RankAdjTempo,OE,RankOE,AdjOE,RankAdjOE,...,RankOppF3GRate,ARate,RankARate,OppARate,RankOppARate,StlRate,RankStlRate,OppStlRate,RankOppStlRate,DefensiveFingerprint
0,Air Force,2011,62.5159,322,61.2714,328,102.0310,158,105.7170,107,...,345,69.3098,1,64.2216,339,0.0991,125,0.0863,90,-11.8
1,Akron,2011,66.6580,184,66.2222,147,103.1750,132,103.2900,161,...,97,57.6251,86,51.4110,106,0.0934,165,0.0867,95,9.4
2,Alabama,2011,65.6639,230,63.8506,260,100.6790,193,103.6510,148,...,150,48.8172,284,50.1319,79,0.1441,1,0.0907,137,8.3
3,Alabama A&M,2011,71.2373,27,70.1295,25,87.9417,335,86.2111,339,...,44,52.3466,192,55.8219,235,0.1201,29,0.1134,324,9.7
4,Alabama St.,2011,66.1276,203,63.8590,259,92.1392,317,92.3675,311,...,75,55.7164,116,56.8483,263,0.1089,63,0.1093,308,10.8

In [30]:
# df1.TeamName.unique()

In [52]:
doubles = ["IPFW", "Purdue Fort Wayne", "UT Rio Grande Valley","Fort Wayne","Winston Salem St.","Charleston","Little Rock","Centenary","Louisiana"]

for item in doubles:

    print(f"{item} - {df1.loc[df1.TeamName == item]['Season']}")

IPFW - 124     2011
469     2010
961     2012
1160    2013
1816    2016
2212    2014
2563    2015
Name: Season, dtype: int64
Purdue Fort Wayne - 3374    2019
Name: Season, dtype: int64
UT Rio Grande Valley - 1701    2017
1736    2016
3105    2018
3458    2019
Name: Season, dtype: int64
Fort Wayne - 1474    2017
2878    2018
Name: Season, dtype: int64
Winston Salem St. - 683    2010
Name: Season, dtype: int64
Charleston - 3184    2019
Name: Season, dtype: int64
Little Rock - 1526    2017
2930    2018
3281    2019
Name: Season, dtype: int64
Centenary - 41     2011
386    2010
Name: Season, dtype: int64
Louisiana - 3285    2019
Name: Season, dtype: int64

In [11]:
# os.chdir('..')
mapping = pd.read_csv('./data/sref_kenpom_map.csv')

In [13]:
mapping.head(20)

              sportsref               KenPom
0     abilene-christian    Abilene Christian
1             air-force            Air Force
2                 akron                Akron
3               alabama              Alabama
4            alabama-am          Alabama A&M
5         alabama-state          Alabama St.
6    alabama-birmingham                  UAB
7             albany-ny               Albany
8          alcorn-state           Alcorn St.
9              american             American
10    appalachian-state      Appalachian St.
11              arizona              Arizona
12        arizona-state          Arizona St.
13             arkansas             Arkansas
14       arkansas-state         Arkansas St.
15  arkansas-pine-bluff  Arkansas Pine Bluff
16                 army                 Army
17               auburn               Auburn
18          austin-peay          Austin Peay
19           ball-state             Ball St.

In [64]:
SR_to_KP_dict = mapping.set_index('sportsref').to_dict()['KenPom']

In [66]:
KP_to_SR_dict = mapping.set_index('KenPom').to_dict()['sportsref']

In [2]:
# KP_to_SR_dict